# Generated by Django 4.1.3 on 2022-12-05 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_remove_group_pets_alter_group_scientific_name"),
        ("traits", "0001_initial"),
        ("pets", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="group",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="group",
                to="groups.group",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pet",
            name="traits",
            field=models.ManyToManyField(related_name="traits", to="traits.trait"),
        ),
    ]
