# Generated by Django 4.1.3 on 2022-12-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0002_trait_name_trait_pets"),
        ("pets", "0002_pet_age_pet_name_pet_sex_pet_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="traits",
            field=models.ManyToManyField(related_name="Traits", to="traits.trait"),
        ),
    ]
