# Generated by Django 4.1.3 on 2022-12-05 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0008_remove_group_pets"),
        ("pets", "0004_remove_pet_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="groups",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="groups.group",
            ),
        ),
    ]
