# Generated by Django 4.1.3 on 2022-12-05 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0005_pet_groups"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pet",
            old_name="groups",
            new_name="group",
        ),
    ]
