# Generated by Django 4.1.3 on 2022-12-05 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0006_rename_groups_pet_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="group",
        ),
    ]
