# Generated by Django 4.1.3 on 2022-12-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0001_initial"),
        ("pets", "0007_remove_pet_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="traits",
            field=models.ManyToManyField(related_name="Traits", to="traits.trait"),
        ),
    ]
