# Generated by Django 4.1.3 on 2022-12-03 17:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0002_pet_age_pet_name_pet_sex_pet_weight"),
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="create_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="pets",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="Group",
                to="pets.pet",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="scientific_name",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
