# Generated by Django 4.1.3 on 2022-12-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="pets",
        ),
        migrations.AlterField(
            model_name="group",
            name="scientific_name",
            field=models.CharField(default=" ", max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
