# Generated by Django 4.1.3 on 2022-12-05 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0004_remove_pet_group"),
        ("groups", "0005_alter_group_pets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="pets",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="group",
                to="pets.pet",
            ),
        ),
    ]
